# Generated by Django 4.0.3 on 2022-03-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0002_alter_authorbook_table_alter_book_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
    ]
