# Generated by Django 4.0.3 on 2022-03-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0003_rename_author_age_author_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='Bookss',
        ),
    ]
