# Generated by Django 4.0.3 on 2022-03-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0004_rename_book_bookss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookss',
            new_name='Book',
        ),
    ]
