# Generated by Django 4.0.3 on 2022-03-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MtoA',
            new_name='MovieActor',
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='actors_movie', through='starring.MovieActor', to='starring.movie'),
        ),
    ]
