# Generated by Django 4.0.3 on 2022-03-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starring', '0002_rename_mtoa_movieactor_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
    ]
