# Generated by Django 4.0.3 on 2022-03-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starring', '0003_remove_movie_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movie',
            new_name='movies',
        ),
    ]
