# Generated by Django 4.0.3 on 2022-03-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starring', '0004_rename_movie_actor_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movies',
            new_name='moviess',
        ),
    ]
