# Generated by Django 4.0.3 on 2022-03-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starring', '0005_rename_movies_actor_moviess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='moviess',
            new_name='movies',
        ),
    ]
